version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  mqtt:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1884:1884"
      - "9001:9001"
  mqtt-ui:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-ui
    restart: unless-stopped
    ports:
      - "4000:4000"