version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: nft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TS_TELEMETRY: "off"
    ports:
      - "5432:5432"
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  mqtt-ui:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-ui
    restart: unless-stopped
    ports:
      - "4000:4000"
