DROP TABLE IF EXISTS user_identity;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS app_user_permissions;
DROP TABLE IF EXISTS app_user;

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(128),
    picture_url VARCHAR(512),
    phone VARCHAR(32),
    order_confirmation_emails BOOLEAN DEFAULT TRUE NOT NULL,
    pickup_ready_notification BOOLEAN DEFAULT TRUE NOT NULL,
    role VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL,
    email_verified BOOLEAN DEFAULT FALSE NOT NULL,
    status VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
    invited BOOLEAN DEFAULT FALSE NOT NULL,
    invited_at TIMESTAMP,
    invite_token_hash VARCHAR(128),
    invite_expires_at TIMESTAMP,
    invite_used_at TIMESTAMP,
    password_reset_token_hash VARCHAR(255),
    password_reset_expires_at TIMESTAMP,
    password_reset_used_at TIMESTAMP,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE app_user_permissions (
    user_id BIGINT NOT NULL,
    permission VARCHAR(64) NOT NULL,
    CONSTRAINT fk_app_user_permissions_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

CREATE TABLE user_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_identity_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT ux_user_identity_provider_subject UNIQUE (provider, provider_subject)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    issued_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    user_agent VARCHAR(255),
    ip VARCHAR(64),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);
