DROP TABLE IF EXISTS app_user_permissions;
DROP TABLE IF EXISTS app_user;

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(128),
    role VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL,
    status VARCHAR(32) NOT NULL,
    invited BOOLEAN NOT NULL,
    invite_token_hash VARCHAR(128),
    invite_expires_at TIMESTAMP,
    invite_used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE app_user_permissions (
    user_id BIGINT NOT NULL,
    permission VARCHAR(64) NOT NULL,
    CONSTRAINT fk_app_user_permissions_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);
