--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-14 21:59:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3470 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16398)
-- Name: device; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device (
    composite_id character varying(128) NOT NULL,
    device_id character varying(64) NOT NULL,
    layer character varying(16) NOT NULL,
    system character varying(16) NOT NULL,
    group_id bigint NOT NULL
);


ALTER TABLE public.device OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16404)
-- Name: device_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device_group (
    id bigint NOT NULL,
    mqtt_topic character varying(255)
);


ALTER TABLE public.device_group OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16403)
-- Name: device_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.device_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16385)
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16410)
-- Name: oxygen_pump_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oxygen_pump_status (
    id bigint NOT NULL,
    status boolean NOT NULL,
    status_time timestamp(6) with time zone NOT NULL,
    composite_id character varying(128) NOT NULL
);


ALTER TABLE public.oxygen_pump_status OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16409)
-- Name: oxygen_pump_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oxygen_pump_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oxygen_pump_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16416)
-- Name: sensor_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sensor_data (
    id bigint NOT NULL,
    sensor_type character varying(64) NOT NULL,
    unit character varying(32),
    sensor_value double precision,
    record_id bigint NOT NULL
);


ALTER TABLE public.sensor_data OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16415)
-- Name: sensor_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sensor_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensor_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16422)
-- Name: sensor_health_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sensor_health_item (
    id bigint NOT NULL,
    sensor_type character varying(64) NOT NULL,
    status boolean NOT NULL,
    record_id bigint NOT NULL
);


ALTER TABLE public.sensor_health_item OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16421)
-- Name: sensor_health_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sensor_health_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensor_health_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16428)
-- Name: sensor_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sensor_record (
    id bigint NOT NULL,
    record_time timestamp(6) with time zone NOT NULL,
    device_composite_id character varying(128) NOT NULL
);


ALTER TABLE public.sensor_record OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16427)
-- Name: sensor_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sensor_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensor_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3299 (class 2606 OID 16408)
-- Name: device_group device_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device_group
    ADD CONSTRAINT device_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3293 (class 2606 OID 16402)
-- Name: device device_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (composite_id);


--
-- TOC entry 3290 (class 2606 OID 16392)
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- TOC entry 3304 (class 2606 OID 16414)
-- Name: oxygen_pump_status oxygen_pump_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oxygen_pump_status
    ADD CONSTRAINT oxygen_pump_status_pkey PRIMARY KEY (id);


--
-- TOC entry 3307 (class 2606 OID 16420)
-- Name: sensor_data sensor_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_data
    ADD CONSTRAINT sensor_data_pkey PRIMARY KEY (id);


--
-- TOC entry 3312 (class 2606 OID 16426)
-- Name: sensor_health_item sensor_health_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_health_item
    ADD CONSTRAINT sensor_health_item_pkey PRIMARY KEY (id);


--
-- TOC entry 3317 (class 2606 OID 16432)
-- Name: sensor_record sensor_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_record
    ADD CONSTRAINT sensor_record_pkey PRIMARY KEY (id);


--
-- TOC entry 3309 (class 2606 OID 16442)
-- Name: sensor_data ux_data_record_type; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_data
    ADD CONSTRAINT ux_data_record_type UNIQUE (record_id, sensor_type);


--
-- TOC entry 3301 (class 2606 OID 16438)
-- Name: device_group ux_device_group_mqtt_topic; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device_group
    ADD CONSTRAINT ux_device_group_mqtt_topic UNIQUE (mqtt_topic);


--
-- TOC entry 3297 (class 2606 OID 16436)
-- Name: device ux_device_system_layer_deviceid; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT ux_device_system_layer_deviceid UNIQUE (system, layer, device_id);


--
-- TOC entry 3314 (class 2606 OID 16445)
-- Name: sensor_health_item ux_health_record_type; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_health_item
    ADD CONSTRAINT ux_health_record_type UNIQUE (record_id, sensor_type);


--
-- TOC entry 3291 (class 1259 OID 16393)
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- TOC entry 3305 (class 1259 OID 16440)
-- Name: ix_data_record; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_data_record ON public.sensor_data USING btree (record_id);


--
-- TOC entry 3294 (class 1259 OID 16434)
-- Name: ix_device_device_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_device_device_id ON public.device USING btree (device_id);


--
-- TOC entry 3295 (class 1259 OID 16433)
-- Name: ix_device_system_layer; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_device_system_layer ON public.device USING btree (system, layer);


--
-- TOC entry 3310 (class 1259 OID 16443)
-- Name: ix_health_record; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_health_record ON public.sensor_health_item USING btree (record_id);


--
-- TOC entry 3302 (class 1259 OID 16439)
-- Name: ix_ops_device_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ops_device_time ON public.oxygen_pump_status USING btree (composite_id, status_time DESC);


--
-- TOC entry 3315 (class 1259 OID 16446)
-- Name: ix_record_device_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_record_device_time ON public.sensor_record USING btree (device_composite_id, record_time DESC);


--
-- TOC entry 3322 (class 2606 OID 16467)
-- Name: sensor_record fk3htlu6nreu14cpnq0v4eswtic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_record
    ADD CONSTRAINT fk3htlu6nreu14cpnq0v4eswtic FOREIGN KEY (device_composite_id) REFERENCES public.device(composite_id);


--
-- TOC entry 3320 (class 2606 OID 16457)
-- Name: sensor_data fk4d0gbn40sr11sknct2c81726g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_data
    ADD CONSTRAINT fk4d0gbn40sr11sknct2c81726g FOREIGN KEY (record_id) REFERENCES public.sensor_record(id);


--
-- TOC entry 3319 (class 2606 OID 16452)
-- Name: oxygen_pump_status fk9494bk670ugibat45o7r37bi3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oxygen_pump_status
    ADD CONSTRAINT fk9494bk670ugibat45o7r37bi3 FOREIGN KEY (composite_id) REFERENCES public.device(composite_id);


--
-- TOC entry 3321 (class 2606 OID 16462)
-- Name: sensor_health_item fkju56g8nex10uab6bmfh83yfy5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_health_item
    ADD CONSTRAINT fkju56g8nex10uab6bmfh83yfy5 FOREIGN KEY (record_id) REFERENCES public.sensor_record(id);


--
-- TOC entry 3318 (class 2606 OID 16447)
-- Name: device fkrcdgnc038im6y3rs1nbt101yc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT fkrcdgnc038im6y3rs1nbt101yc FOREIGN KEY (group_id) REFERENCES public.device_group(id);


-- Completed on 2025-08-14 21:59:57

--
-- PostgreSQL database dump complete
--

